language: node_js
sudo: false
node_js:
  - "6.11"
install:
  - npm install -g jasmine
  - npm install -g istanbul
  - npm install -g codecov
  - npm install
  - npm install --only=dev
script:
  - npm test
  - npm run report-coverage
